<a href="https://colab.research.google.com/github/AnuragTiwari-hub/AIML/blob/main/AIML_13(min_max).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving SOCR-HeightWeight.csv to SOCR-HeightWeight.csv


In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Sample data
data = pd.read_csv('SOCR-HeightWeight.csv')

# Initialize the scaler
scaler = MinMaxScaler()

# Fit and transform the data
normalized_data = scaler.fit_transform(data)
print("Normalized Data (Min-Max Scaling):")
print(normalized_data)

Normalized Data (Min-Max Scaling):
[[0.00000000e+00 3.70094605e-01 3.76472136e-01]
 [4.00016001e-05 7.55446928e-01 6.29351182e-01]
 [8.00032001e-05 6.13157874e-01 8.07370074e-01]
 ...
 [9.99919997e-01 2.97166818e-01 4.33226448e-01]
 [9.99959998e-01 4.87468436e-01 5.83940198e-01]
 [1.00000000e+00 5.78122605e-01 5.04357155e-01]]


In [ ]:
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = StandardScaler()

# Fit and transform the data
standardized_data = scaler.fit_transform(data)
print("Standardized Data (Z-score Normalization):")
print(standardized_data)

Standardized Data (Z-score Normalization):
[[-1.73198153 -1.16205104 -1.20807192]
 [-1.73184296  1.85213554  0.8068047 ]
 [-1.7317044   0.73916507  2.22521445]
 ...
 [ 1.7317044  -1.73248476 -0.75586784]
 [ 1.73184296 -0.2439649   0.44498141]
 [ 1.73198153  0.46512277 -0.18911625]]
